mobility_dbt_profile:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-worker
      port: 10000
      schema: mobility_lakehouse
      threads: 4
      connect_timeout: 60
      connect_retries: 3
